# Generated by Django 6.0.4 on 2026-05-15 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=80)),
                ('email', models.EmailField(max_length=100)),
                ('numero', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Profissional',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=80)),
                ('email', models.EmailField(max_length=100)),
                ('numero', models.CharField(max_length=15)),
            ],
        ),
    ]
