# Generated by Django 6.0.5 on 2026-06-01 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=80)),
                ('email', models.EmailField(max_length=100)),
                ('numero', models.CharField(max_length=15)),
                ('senha', models.CharField(max_length=100)),
                ('tipo', models.CharField(choices=[('CLIENTE', 'Cliente'), ('PROFISSIONAL', 'Profissional')], default='CLIENTE', max_length=20)),
            ],
        ),
    ]
