# Generated by Django 6.0.4 on 2026-05-27 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profissional',
            name='senha',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
