# Generated by Django 6.0.5 on 2026-06-01 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_profissional_senha'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profissional',
        ),
        migrations.AddField(
            model_name='cliente',
            name='tipo',
            field=models.CharField(choices=[('CLIENTE', 'Cliente'), ('PROFISSIONAL', 'Profissional')], default='CLIENTE', max_length=20),
        ),
    ]
