# Generated by Django 6.0.4 on 2026-05-15 15:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0002_alter_cliente_id_alter_profissional_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Agenta',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('data', models.DateField()),
                ('hora', models.DateTimeField()),
                ('servicoFK', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.cliente')),
            ],
        ),
    ]
