# Generated by Django 6.0.5 on 2026-06-01 00:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0003_delete_profissional_cliente_tipo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Servicos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=70)),
                ('preco', models.DecimalField(decimal_places=2, max_digits=6)),
            ],
            options={
                'verbose_name': 'Servico',
                'verbose_name_plural': 'Servicos',
            },
        ),
        migrations.CreateModel(
            name='Agenda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('hora', models.TimeField()),
                ('clienteFk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agendamentos', to='accounts.cliente')),
                ('profissionalFk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agendamentos_profissional', to='accounts.cliente')),
            ],
        ),
        migrations.CreateModel(
            name='AgendaServico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agenda', models.ForeignKey(db_column='agenda_id', on_delete=django.db.models.deletion.CASCADE, related_name='agenda_servicos', to='appointments.agenda')),
                ('servico', models.ForeignKey(db_column='servico_id', on_delete=django.db.models.deletion.CASCADE, related_name='agenda_servicos', to='appointments.servicos')),
            ],
            options={
                'verbose_name': 'Agenda servico',
                'verbose_name_plural': 'Agenda servicos',
                'db_table': 'AgendaServico',
            },
        ),
    ]
