# Arquivo de migration deletado - será recriado via makemigrations
# Generated by Django 6.0.4 on 2026-05-15 20:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
    ]
