# Generated by Django 6.0.4 on 2026-05-27 19:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_profissional_senha'),
        ('appointments', '0003_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Agenda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('hora', models.DateTimeField()),
                ('profissionalFk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.profissional')),
                ('servicoFK', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.cliente')),
            ],
        ),
        migrations.DeleteModel(
            name='Agenta',
        ),
    ]
